2016-05-03 18:05:03.109 INFO [pool-2-thread-1][SynchronizeDataTask.java:30] - running SynchronizeData......
 2016-05-03 18:07:48.124 ERROR [pool-2-thread-1][SynchronizeDataTask.java:35] - bti_1no Data
 2016-05-03 18:07:51.781 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - bti_120=====> [ 新增了132条数据 ]
 2016-05-03 18:07:52.080 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - bti_1440=====> [ 新增了11条数据 ]
 2016-05-03 18:08:27.253 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - bti_15=====> [ 新增了1025条数据 ]
 2016-05-03 18:08:29.448 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - bti_240=====> [ 新增了66条数据 ]
 2016-05-03 18:09:31.088 ERROR [pool-2-thread-1][SynchronizeDataTask.java:35] - bti_3no Data
 2016-05-03 18:09:45.884 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - bti_30=====> [ 新增了523条数据 ]
 2016-05-03 18:09:48.043 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - bti_360=====> [ 新增了44条数据 ]
 2016-05-03 18:09:53.940 ERROR [pool-2-thread-1][SynchronizeDataTask.java:35] - bti_5no Data
 2016-05-03 18:10:07.086 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - bti_60=====> [ 新增了262条数据 ]
 2016-05-03 18:10:08.264 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - bti_720=====> [ 新增了22条数据 ]
 2016-05-03 18:10:14.454 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - lsi_120=====> [ 新增了119条数据 ]
 2016-05-03 18:10:15.276 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - lsi_1440=====> [ 新增了11条数据 ]
 2016-05-03 18:10:18.442 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - lsi_240=====> [ 新增了64条数据 ]
 2016-05-03 18:10:20.765 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - lsi_360=====> [ 新增了43条数据 ]
 2016-05-03 18:10:31.254 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - lsi_60=====> [ 新增了225条数据 ]
 2016-05-03 18:10:32.536 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - lsi_720=====> [ 新增了22条数据 ]
 2016-05-03 18:10:39.257 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - newbie_china_btc_120=====> [ 新增了132条数据 ]
 2016-05-03 18:10:39.419 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - newbie_china_btc_1440=====> [ 新增了0条数据 ]
 2016-05-03 18:10:43.312 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - newbie_china_btc_240=====> [ 新增了66条数据 ]
 2016-05-03 18:10:45.768 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - newbie_china_btc_360=====> [ 新增了44条数据 ]
 2016-05-03 18:10:58.292 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - newbie_china_btc_60=====> [ 新增了255条数据 ]
 2016-05-03 18:10:59.824 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - newbie_china_btc_720=====> [ 新增了22条数据 ]
 2016-05-03 18:15:00.016 INFO [pool-2-thread-1][SynchronizeDataTask.java:30] - running SynchronizeData......
 2016-05-03 18:15:05.521 ERROR [pool-2-thread-1][SynchronizeDataServiceImpl.java:111] - org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into bti_1 (date,indx,info) values (' 2015-12-11 18:25:00 ',  19.0 ,' null') ]; Duplicate entry '2015-12-11 18:25:00' for key 'date'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2015-12-11 18:25:00' for key 'date'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:416)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:440)
	at com.radarwin.bifu.bm.dao.impl.SynchronizeDataDaoImpl.save(SynchronizeDataDaoImpl.java:221)
	at com.radarwin.bifu.bm.service.impl.SynchronizeDataServiceImpl.addNewData(SynchronizeDataServiceImpl.java:107)
	at com.radarwin.bifu.bm.task.base.SynchronizeDataTask.syn(SynchronizeDataTask.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2015-12-11 18:25:00' for key 'date'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2489)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:848)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:742)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2489)
	at com.alibaba.druid.filter.FilterAdapter.statement_execute(FilterAdapter.java:2451)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_execute(FilterEventAdapter.java:188)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2487)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.execute(StatementProxyImpl.java:137)
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:421)
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:432)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:405)
	... 18 more

 2016-05-03 18:15:05.736 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - bti_120=====> [ 新增了0条数据 ]
 2016-05-03 18:15:05.960 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - bti_1440=====> [ 新增了0条数据 ]
 2016-05-03 18:15:06.136 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - bti_15=====> [ 新增了0条数据 ]
 2016-05-03 18:15:06.727 INFO [pool-2-thread-1][SynchronizeDataServiceImpl.java:109] - bti_240=====> [ 新增了0条数据 ]
 2016-05-03 18:18:35.526 ERROR [main][SynchronizeDataServiceImpl.java:111] - org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [insert into bti_1 (date,indx,info) values (' 2015-12-18 18:41:00 ',  15.0 ,' null') ]; Duplicate entry '2015-12-18 18:41:00' for key 'date'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2015-12-18 18:41:00' for key 'date'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:416)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:440)
	at com.radarwin.bifu.bm.dao.impl.SynchronizeDataDaoImpl.save(SynchronizeDataDaoImpl.java:205)
	at com.radarwin.bifu.bm.service.impl.SynchronizeDataServiceImpl.addNewData(SynchronizeDataServiceImpl.java:107)
	at Test.addNewData(Test.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:73)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:224)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2015-12-18 18:41:00' for key 'date'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2489)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:848)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:742)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2489)
	at com.alibaba.druid.filter.FilterAdapter.statement_execute(FilterAdapter.java:2451)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_execute(FilterEventAdapter.java:188)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2487)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.execute(StatementProxyImpl.java:137)
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:421)
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:432)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:405)
	... 36 more

 2016-05-03 18:18:35.625 INFO [main][SynchronizeDataServiceImpl.java:109] - bti_120=====> [ 新增了0条数据 ]
 2016-05-03 18:18:35.695 INFO [main][SynchronizeDataServiceImpl.java:109] - bti_1440=====> [ 新增了0条数据 ]
 2016-05-03 18:18:35.764 INFO [main][SynchronizeDataServiceImpl.java:109] - bti_15=====> [ 新增了1条数据 ]
 2016-05-03 18:18:35.826 INFO [main][SynchronizeDataServiceImpl.java:109] - bti_240=====> [ 新增了0条数据 ]
 